import {
  FaBuilding,
  FaHouse,
  FaHouseUser,
  FaCity,
  FaWarehouse,
  FaShop,
  FaRulerCombined,
  FaScrewdriverWrench,
  FaCompass,
  FaHammer,
  FaPenRuler,
  FaFileContract,
  FaKey,
  FaClipboardList,
  FaHandshake,
  FaFolderOpen,
  FaMoneyBillWave,
  FaReceipt,
  FaCalculator,
  FaChartLine,
  FaTags,
  FaPercent,
  FaUserTie,
  FaUsers,
  FaUserGear,
  FaUserCheck,
  FaLocationDot,
  FaMapLocationDot,
  FaShieldHalved,
  FaTruckPickup,
  FaLayerGroup,
  FaClock,
  FaPhone,
  FaEnvelope,
  FaComments,
  FaGlobe,
} from "react-icons/fa6";

export const FEATURE_ICONS = [
  "building",
  "house",
  "house_user",
  "city",
  "warehouse",
  "shop",
  "ruler_combined",
  "pen_ruler",
  "compass",
  "layer_group",
  "screwdriver_wrench",
  "hammer",
  "truck_pickup",
  "shield_halved",
  "file_contract",
  "key",
  "clipboard_list",
  "handshake",
  "folder_open",
  "money_bill_wave",
  "receipt",
  "calculator",
  "chart_line",
  "tags",
  "percent",
  "user_tie",
  "users",
  "user_gear",
  "user_check",
  "location_dot",
  "map_location_dot",
  "clock",
  "phone",
  "envelope",
  "comments",
  "globe",
] as const;

export const FEATURE_ICONS_MAP = {
  default: FaBuilding,
  building: FaBuilding,
  house: FaHouse,
  house_user: FaHouseUser,
  city: FaCity,
  warehouse: FaWarehouse,
  shop: FaShop,
  ruler_combined: FaRulerCombined,
  pen_ruler: FaPenRuler,
  compass: FaCompass,
  layer_group: FaLayerGroup,
  screwdriver_wrench: FaScrewdriverWrench,
  hammer: FaHammer,
  truck_pickup: FaTruckPickup,
  shield_halved: FaShieldHalved,
  file_contract: FaFileContract,
  key: FaKey,
  clipboard_list: FaClipboardList,
  handshake: FaHandshake,
  folder_open: FaFolderOpen,
  money_bill_wave: FaMoneyBillWave,
  receipt: FaReceipt,
  calculator: FaCalculator,
  chart_line: FaChartLine,
  tags: FaTags,
  percent: FaPercent,
  user_tie: FaUserTie,
  users: FaUsers,
  user_gear: FaUserGear,
  user_check: FaUserCheck,
  location_dot: FaLocationDot,
  map_location_dot: FaMapLocationDot,
  clock: FaClock,
  phone: FaPhone,
  envelope: FaEnvelope,
  comments: FaComments,
  globe: FaGlobe,
} as const;